
//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Cellenza.Service.Data
{

using System;
    using System.Collections.Generic;
    
public partial class ActiviteTable
{

    public int ID { get; set; }

    public int CompteRenduActiviteTableID { get; set; }

    public int Type { get; set; }

    public string Comment { get; set; }

    public bool Afternoon { get; set; }

    public Nullable<int> MissionTableID { get; set; }

    public int Day { get; set; }



    public virtual CompteRenduActiviteTable CompteRenduActiviteTable { get; set; }

    public virtual MissionTable MissionTable { get; set; }

}

}
