//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StaffingWebService.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ActiviteTable
    {
        public int ID { get; set; }
        public int CompteRenduActiviteTableID { get; set; }
        public int Type { get; set; }
        public string Comment { get; set; }
        public bool Afternoon { get; set; }
        public Nullable<int> MissionTableID { get; set; }
        public int Day { get; set; }
    
        public virtual CompteRenduActiviteTable CompteRenduActiviteTable { get; set; }
        public virtual MissionTable MissionTable { get; set; }
    }
}
