
//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Cellenza.Service.Data
{

using System;
    using System.Collections.Generic;
    
public partial class ClientTable
{

    public ClientTable()
    {

        this.MissionTable = new HashSet<MissionTable>();

    }


    public int ID { get; set; }

    public string RaisonSociale { get; set; }

    public string CodeClient { get; set; }

    public string Image { get; set; }

    public bool Actif { get; set; }



    public virtual ICollection<MissionTable> MissionTable { get; set; }

}

}
