
//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Cellenza.Service.Data
{

using System;
    using System.Collections.Generic;
    
public partial class CompteRenduActiviteTable
{

    public CompteRenduActiviteTable()
    {

        this.ActiviteTable = new HashSet<ActiviteTable>();

    }


    public int ID { get; set; }

    public int ConsultantTableID { get; set; }

    public int Year { get; set; }

    public int Month { get; set; }

    public int Status { get; set; }



    public virtual ICollection<ActiviteTable> ActiviteTable { get; set; }

    public virtual ConsultantTable ConsultantTable { get; set; }

}

}
