//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StaffingWebService.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConsultantTable
    {
        public ConsultantTable()
        {
            this.Actif = true;
            this.Admin = false;
            this.CompteRenduActiviteTable = new HashSet<CompteRenduActiviteTable>();
            this.VacanceTable = new HashSet<VacanceTable>();
        }
    
        public int ID { get; set; }
        public string Nom { get; set; }
        public string Prenom { get; set; }
        public Nullable<System.DateTime> DateNaissance { get; set; }
        public string NoSecu { get; set; }
        public string Email { get; set; }
        public Nullable<System.DateTime> DateArrivee { get; set; }
        public Nullable<System.DateTime> DateDepart { get; set; }
        public string Image { get; set; }
        public bool Actif { get; set; }
        public bool Admin { get; set; }
        public string Poste { get; set; }
        public string AdresseRue { get; set; }
        public string AdresseComplement { get; set; }
        public string AdresseCodePostal { get; set; }
        public string AdresseVille { get; set; }
        public string LiveEmail { get; set; }
    
        public virtual ICollection<CompteRenduActiviteTable> CompteRenduActiviteTable { get; set; }
        public virtual ICollection<VacanceTable> VacanceTable { get; set; }
    }
}
