//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StaffingWebService.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class MissionTable
    {
        public MissionTable()
        {
            this.Actif = true;
            this.ActiviteTable = new HashSet<ActiviteTable>();
        }
    
        public int ID { get; set; }
        public string Intitule { get; set; }
        public int ConsultantTableID { get; set; }
        public Nullable<System.DateTime> DateDebut { get; set; }
        public Nullable<System.DateTime> DateFin { get; set; }
        public string ReferenceFacturation { get; set; }
        public Nullable<System.DateTime> DateFacturation { get; set; }
        public Nullable<int> Facturation { get; set; }
        public string Image { get; set; }
        public bool Actif { get; set; }
        public string InterlocuteurNom { get; set; }
        public string InterlocuteurTelephone { get; set; }
        public string InterlocuteurEmail { get; set; }
        public int ClientTableID { get; set; }
    
        public virtual ICollection<ActiviteTable> ActiviteTable { get; set; }
        public virtual ClientTable ClientTable { get; set; }
    }
}
