
//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Cellenza.Service.Data
{

using System;
    using System.Collections.Generic;
    
public partial class MissionTable
{

    public MissionTable()
    {

        this.Actif = true;

        this.ActiviteTable = new HashSet<ActiviteTable>();

    }


    public int ID { get; set; }

    public string Intitule { get; set; }

    public int ConsultantTableID { get; set; }

    public Nullable<System.DateTime> DateDebut { get; set; }

    public Nullable<System.DateTime> DateFin { get; set; }

    public string ReferenceFacturation { get; set; }

    public Nullable<System.DateTime> DateFacturation { get; set; }

    public Nullable<int> Facturation { get; set; }

    public string Image { get; set; }

    public bool Actif { get; set; }

    public string InterlocuteurNom { get; set; }

    public string InterlocuteurTelephone { get; set; }

    public string InterlocuteurEmail { get; set; }

    public int ClientTableID { get; set; }



    public virtual ICollection<ActiviteTable> ActiviteTable { get; set; }

    public virtual ClientTable ClientTable { get; set; }

}

}
