//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StaffingWebService.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class StaffingModelContainer : DbContext
    {
        public StaffingModelContainer()
            : base("name=StaffingModelContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<ConsultantTable> ConsultantTable { get; set; }
        public DbSet<MissionTable> MissionTable { get; set; }
        public DbSet<ActiviteTable> ActiviteTable { get; set; }
        public DbSet<CompteRenduActiviteTable> CompteRenduActiviteTable { get; set; }
        public DbSet<VacanceTable> VacanceTable { get; set; }
        public DbSet<ClientTable> ClientTable { get; set; }
    }
}
