

//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Cellenza.Service.Data
{

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;


public partial class StaffingModelContainer : DbContext
{
    public StaffingModelContainer()
        : base("name=StaffingModelContainer")
    {

    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }


    public DbSet<ConsultantTable> ConsultantTable { get; set; }

    public DbSet<MissionTable> MissionTable { get; set; }

    public DbSet<ActiviteTable> ActiviteTable { get; set; }

    public DbSet<CompteRenduActiviteTable> CompteRenduActiviteTable { get; set; }

    public DbSet<VacanceTable> VacanceTable { get; set; }

    public DbSet<ClientTable> ClientTable { get; set; }

}

}

