//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StaffingWebService.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class VacanceTable
    {
        public VacanceTable()
        {
            this.Actif = true;
        }
    
        public int ID { get; set; }
        public int ConsultantTableID { get; set; }
        public int Type { get; set; }
        public System.DateTime DateDebut { get; set; }
        public System.DateTime DateFin { get; set; }
        public string Motif { get; set; }
        public string Commentaire { get; set; }
        public int Status { get; set; }
        public bool Actif { get; set; }
    
        public virtual ConsultantTable ConsultantTable { get; set; }
    }
}
