
//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Cellenza.Service.Data
{

using System;
    using System.Collections.Generic;
    
public partial class VacanceTable
{

    public VacanceTable()
    {

        this.Actif = true;

    }


    public int ID { get; set; }

    public int ConsultantTableID { get; set; }

    public int Type { get; set; }

    public System.DateTime DateDebut { get; set; }

    public System.DateTime DateFin { get; set; }

    public string Motif { get; set; }

    public string Commentaire { get; set; }

    public int Status { get; set; }

    public bool Actif { get; set; }



    public virtual ConsultantTable ConsultantTable { get; set; }

}

}
